database-path = ""

[ctftime]
ctftime-event = "https://ctftime.org/api/v1/events/?limit=100"
ctftime-writeup = "https://ctftime.org/writeups/rss/"
ctftime-avatar = "https://pbs.twimg.com/profile_images/2189766987/ctftime-logo-avatar_400x400.png"
discord-webhook = ""

[crackmes]
crackmes-latest = "https://crackmes.one/rss/crackme"
crackmes-avatar = "https://i.imgur.com/ZItQiDp.png"
discord-webhook = ""

[github]
github-starred = "https://api.github.com/users/retr4ce/starred"
github-avatar = "https://pbs.twimg.com/profile_images/1414990564408262661/r6YemvF9_400x400.jpg"
discord-webhook = ""